### ISSUE TITLE
Geth passwords should not sit in plaintext in supervisor config

### ISSUE THREAD

**Issue by Lsquared13** [Eximchain/terraform-aws-quorum-cluster#14]
# Problem
Currently, the passwords that encrypt the geth keys are passed to geth via the command line, and they are stored in plaintext in the supervisor config. This makes the password effectively useless at protecting the key.

# Ideal Solution
Geth could, instead of the plaintext password, be passed a location to retrieve the key from in vault. The password could be retrieved from vault by geth directly, and we could avoid persisting the plaintext password in any permanent form.

Other solutions may be acceptable after determining and reviewing a threat model for attacks involving the password.

**Comment by john-osullivan** [comment]
Begun work on this in the following two fork repos, linked here for convenience:
- [john-osullivan/quorum-johno](https://github.com/john-osullivan/quorum-johno) - Accept new flags; API calls to retrieve keys; store found value in memory.
- [john-osullivan/terraform-aws-quorum-cluster-johno](https://github.com/john-osullivan/terraform-aws-quorum-cluster-johno) - Modifies the `init-quorum.sh` script to add `--vaultaddr` and `--vaultpwpath` as arguments to the `geth` command.

**Comment by john-osullivan** [comment]
### Status Update
This issue is now in cleanup phase.  

- [x] `quorum-johno` now successfully uses the `--vaultaddr`, `--vaultpasswordpath`, `--vaultprefix`, and `--vaultpasswordname` to retrieve the password value out of Vault.  Those args and their usage are documented further on the repository.  Behavior remains unchanged if those arguments are not all provided -- we either use the plaintext string args or we load passwords from the file path.
- [x] The `terraform` repo didn't require many modifications: one C build dependency (`libsasl2-dev`) was added to `build-deps.sh`, and `init-quorum.sh` now has a line which adds the required arguments to the `geth` command.
- [x] Last Mile Problem: The password we're retrieving from Vault was failing to unlock the accounts because it was being saved wrapped in quotes.  This wasn't an issue when they were passed as plaintext because `geth cmd` is friendly and tries to unwrap string args.  They're now being saved properly, so things are behaving.

I'm now squashing commits and wrapping up two PRs, should be ready by EOD.

Edit: Didn't quite get them in by EOD, but here are links to both:
- [quorum: Load account passwords from Vault using CLI args](https://github.com/Eximchain/quorum/pull/3)
- [terraform-...: Removed plaintext passwords from generated quorum scripts](https://github.com/Eximchain/terraform-aws-quorum-cluster/pull/18)

**Comment by Lsquared13** [comment]
Complete with PR #19
