### ISSUE TITLE
Vault permissions should be more finely tuned

### ISSUE THREAD

**Issue by Lsquared13** [Eximchain/terraform-aws-quorum-cluster#21]
# Problem

Currently, everything stored in the vault can be read by any quorum node. While this is intended for 'public' information like addresses, it is not ideal for 'private' information like passwords. Ideally, every node can only read its own private data.

The primary caveat is that all quorum nodes currently use the same IAM role.

# Acceptance Criteria

- A given quorum node can only read or write its own password
- A given quorum node can only write its own address
- A quorum node can read any node's address

**Comment by john-osullivan** [comment]
[Current Policy](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/packer/vault-policies/quorum-node.hcl) gives everyone access everywhere.  Afterwards:
- `addresses`, `makers`, `validators`, `observers`, `bootnodes/addresses` should be `read` access for all nodes.  `write` access for the owners.
  - [`broadcast_role_info`](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/packer/instance-scripts/init-quorum.sh#L204) is where quorum writes the node address to Vault
- `keys`, `passwords`, `bootnodes/keys`, `bootnodes/passwords` are private data, only accessible by the owner.  Full RWU access for owners, nothing elsewhere
- [File which assigns policies: generate-setup-vault](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/packer/instance-scripts/generate-setup-vault.sh), [actual line](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/packer/instance-scripts/generate-setup-vault.sh#L44)
- Right now we [make one IAM role per region that has nodes](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/terraform/modules/quorum-cluster-region/quorum.tf#L533).  That breaks down because nodes are being identified by that IAM Role, and we need diff nodes to have diff identities.  Instead create one IAM role for each node -- from AWS's view, they all act the same and should have the same policy, but we need them to be distinguishable from Vault.
- [Script calling generate-setup-vault](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/terraform/modules/quorum-vault/user-data/user-data-vault.sh#L26)

**Comment by john-osullivan** [comment]
This is my second priority after the bootnode replacement issue, but I'll be working on it when things are building over there.  Work on this issue will be going on the [narrow-vault-policies](https://github.com/john-osullivan/terraform-aws-quorum-cluster-johno/tree/narrow-vault-policies) branch of my fork.

**Comment by john-osullivan** [comment]
First draft of the fix on this is in!
