### ISSUE TITLE
Regionalize Backup Procedure

### ISSUE THREAD

**Issue by Lsquared13** [Eximchain/terraform-aws-quorum-cluster#32]
# Problem

Currently, the S3 backup procedure implemented in [this script](https://github.com/Eximchain/terraform-aws-quorum-cluster/blob/master/packer/instance-scripts/backup-chain-data.py) currently backs up the entire network to a single S3 bucket. This results in backups costing more money than they need to, since we pay for cross-region traffic. In particular, restoration will involve downloading the full chain data from every node.

# Acceptance Criteria

- There is an S3 backup bucket in each region there are quorum nodes
- Nodes back up to and restore from their own region's bucket by default
- There is a command line option to override the backup bucket name, in case we want to force use of another region's bucket.

**Comment by john-osullivan** [comment]
**Update: This turned out to be much quicker than expected, been in a good flow and was able to just crank it out.  Let me know if this PR (#34 ) hits the specs you were looking for, @Lsquared13 .**

Addressing this over on the [regionalized-backups](https://github.com/john-osullivan/terraform-aws-quorum-cluster-johno/tree/regional-backups) branch of my personal repo.  Got the command line overwrite option in there, putting the new backup bucket into `terraform/quorum-cluster-region/main.tf`.

## Design ?s
- Should I make the existing `data_backup_bucket` variable to `quorum-cluster_region` overwrite the automatic value for the region?  Like making override an optional feature, something you can specify for the whole network? If not, any reason not to eliminate that variable?

**Comment by Lsquared13** [comment]
Merged the PR
